### ISSUE TITLE
A request for code of paper “Multi-Modal Answer Validation for Knowledge-Based VQA”

### ISSUE THREAD

**Issue by PengPeixi** [jialinwu17/VilBERTOKVQA#1]
Hello! I am a graduate student. My research is focused on visual question answer. 
I have recently read your paper “Multi-Modal Answer Validation for Knowledge-Based VQA”. I am very interested in this article and have studied it carefully. 
But I got some trouble when I try to implement algorithms. So could you please send me the source program and the necessary information about it which would give me a great of help in comprehending your algorithms. 
I promise they will be used only for research purpose.
Thank you very much for your kind consideration and I am looking forward to your reply.

**Comment by jialinwu17** [comment]
Hi @PengPeixi ，
First of all, thanks for your interest in our work!! However, in fact, the paper is still under review, and the arxiv version is not the final version. As we are still working on finalizing the paper, I may not be able to release the code until the paper being accepted. So sorry for that! You may want to look at the [KRISP model](https://arxiv.org/abs/2012.11014) if you are interested in OKVQA.
Actually, this is not supposed to be the repo for future release, this repo is only a temporary hold for visualization.
